theme: jekyll-theme-cayman
#remote-theme: Sylhare/Type-on-Strap

title: Datengärtnerei                 # Name of website
#avatar: assets/img/triangle.png      # Path of avatar image, to be displayed in the theme's header
description: My thoughts on QA        # Short description, primarily used by search engines
#favicon: assets/favicon.ico          # Icon displayed in the tab
color_theme: auto                     # color theme auto, dark or light
markdown: kramdown
