# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Datengärtnerei QA Pages
email: jensd@datengaertnerei.com
description: >- # this means to ignore newlines until "baseurl:"
  Dies und das über Softwarequalität
twitter_username: datengaertner
github_username: datengaertnerei
minimal_mistakes_skin: default
search: true
locale: "de"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jens Dibbern"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Informatiker, Software Entwickler, Tester schon ein halbes Leben lang. Team Lead bei elbformat."
  links:
    - label: "elbformat"
      icon: "fas fa-briefcase"
      url: "https://elbform.at/"
    - label: "Website"
      icon: "fas fa-home"
      url: "https://www.datengaertnerei.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/datengaertner"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/datengaertnerei"
    - label: "Stackoverflow"
      icon: "fab fa-stack-overflow"
      url: "https://stackoverflow.com/users/story/10937788"
    - label: "Xing"
      icon: "fab fa-xing"
      url: "https://www.xing.com/profile/Jens_Dibbern/portfolio"
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/jensdibbern"

footer:
  links:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
